"""Canonical state-backend API for runtime and governance code."""

from __future__ import annotations

from agentkit.phase_state_store.models import (
    FlowExecution,
    NodeExecutionLedger,
    OverrideRecord,
)
from agentkit.state_backend.exports import (
    CLOSURE_REPORT_FILE,
    CONTEXT_EXPORT_FILE,
    GUARDRAIL_FILE,
    LAYER_ARTIFACT_FILES,
    LEGACY_VERIFY_DECISION_FILE,
    PHASE_STATE_EXPORT_FILE,
    PROTECTED_QA_ARTIFACTS,
    STATE_DB_DIR,
    STATE_DB_FILE,
    VERIFY_DECISION_FILE,
    atomic_write_json,
    state_backend_dir,
    state_db_path,
)
from agentkit.state_backend.records import AttemptRecord, ExecutionReport
from agentkit.state_backend.store import (
    backend_has_completed_snapshot,
    backend_has_structural_artifact,
    backend_has_valid_context,
    backend_has_valid_phase_state,
    load_artifact_record,
    load_attempts,
    load_flow_execution,
    load_latest_verify_decision,
    load_node_execution_ledger,
    load_override_records,
    load_phase_snapshot,
    load_phase_state,
    load_story_context,
    read_artifact_record,
    read_latest_verify_decision_record,
    read_phase_snapshot_record,
    read_phase_state_record,
    read_story_context_record,
    record_closure_report,
    record_layer_artifacts,
    record_verify_decision,
    save_attempt,
    save_flow_execution,
    save_node_execution_ledger,
    save_override_record,
    save_phase_snapshot,
    save_phase_state,
    save_story_context,
)

__all__ = [
    "AttemptRecord",
    "CONTEXT_EXPORT_FILE",
    "CLOSURE_REPORT_FILE",
    "ExecutionReport",
    "FlowExecution",
    "GUARDRAIL_FILE",
    "LAYER_ARTIFACT_FILES",
    "LEGACY_VERIFY_DECISION_FILE",
    "NodeExecutionLedger",
    "OverrideRecord",
    "PHASE_STATE_EXPORT_FILE",
    "PROTECTED_QA_ARTIFACTS",
    "STATE_DB_DIR",
    "STATE_DB_FILE",
    "VERIFY_DECISION_FILE",
    "atomic_write_json",
    "backend_has_completed_snapshot",
    "backend_has_structural_artifact",
    "backend_has_valid_context",
    "backend_has_valid_phase_state",
    "load_artifact_record",
    "load_attempts",
    "load_flow_execution",
    "load_latest_verify_decision",
    "load_node_execution_ledger",
    "load_override_records",
    "load_phase_snapshot",
    "load_phase_state",
    "load_story_context",
    "read_artifact_record",
    "read_latest_verify_decision_record",
    "read_phase_snapshot_record",
    "read_phase_state_record",
    "read_story_context_record",
    "record_closure_report",
    "record_layer_artifacts",
    "record_verify_decision",
    "save_attempt",
    "save_flow_execution",
    "save_node_execution_ledger",
    "save_override_record",
    "save_phase_snapshot",
    "save_phase_state",
    "save_story_context",
    "state_backend_dir",
    "state_db_path",
]
