"""Backing symbol list for the state-backend repository facade boundary.

Holds the literal tuple of public facade symbol names. Kept in this sibling
module so ``public_api`` re-exports the ``PUBLIC_API`` name while staying within
the module-level LOC budget (PY_MODULE_TOP_LEVEL_MAX_LOC_100). The tuple literal
lives inside ``_build_public_api_names`` (a function body, excluded from the
module-level LOC count) and is bound to ``PUBLIC_API_NAMES`` at import time. The
exported tuple contents are identical to the historical ``public_api.PUBLIC_API``
— no symbol added or removed (no behaviour change).
"""

from __future__ import annotations


def _build_public_api_names() -> tuple[str, ...]:
    """Return the immutable, ordered tuple of public facade symbol names."""
    return (
        "append_execution_event",
        "append_execution_event_global",
        "backend_has_completed_snapshot",
        "backend_has_structural_artifact",
        "backend_has_structural_artifact_for_scope",
        "backend_has_valid_context",
        "backend_has_valid_phase_state",
        "backend_verify_decision_passed",
        "backend_verify_decision_passed_for_scope",
        "claim_control_plane_operation_global",
        "commit_control_plane_operation_with_side_effects_global",
        "control_plane_backend_available",
        "count_runtime_execution_residue",
        "delete_control_plane_operation_global",
        "finalize_control_plane_operation_global",
        "finalize_control_plane_start_phase_global",
        "has_committed_control_plane_operation_for_run_global",
        "has_committed_story_exit_operation_for_run_global",
        "release_control_plane_operation_global",
        "takeover_control_plane_operation_global",
        "delete_session_run_binding_global",
        "delete_story_are_link",
        "delete_story_dependency",
        "load_artifact_record",
        "load_artifact_record_for_scope",
        "load_attempts",
        "load_control_plane_operation_global",
        "load_execution_events",
        "load_execution_events_for_project_global",
        "load_execution_events_global",
        "load_flow_execution",
        "load_flow_execution_global",
        "load_json_safe",
        "load_latest_story_metrics_global",
        "load_latest_verify_decision",
        "load_latest_verify_decision_for_scope",
        "load_node_execution_ledger",
        "load_override_records",
        "load_phase_snapshot",
        "load_phase_state",
        "load_phase_state_global",
        "load_project",
        "load_project_by_story_id_prefix",
        "load_projects",
        "load_parallelization_config",
        "load_qa_findings",
        "load_qa_findings_for_scope",
        "load_qa_stage_results",
        "load_qa_stage_results_for_scope",
        "load_session_run_binding_global",
        "load_story_are_links",
        "load_story_context",
        "load_story_context_by_story_number_global",
        "load_story_context_by_uuid_global",
        "load_story_context_global",
        "load_story_contexts_global",
        "load_story_dependencies",
        "load_story_dependency_rows_for_story",
        "load_story_execution_lock_global",
        "load_story_metrics",
        "load_story_metrics_for_scope",
        "purge_attempts",
        "purge_decision_records",
        "purge_execution_events",
        "purge_flow_executions",
        "purge_guard_decisions",
        "purge_node_execution_ledgers",
        "purge_override_records",
        "purge_phase_snapshots",
        "purge_phase_states",
        "purge_run_bound_artifact_envelopes",
        "read_artifact_record",
        "read_latest_verify_decision_record",
        "read_phase_snapshot_record",
        "read_phase_state_record",
        "read_story_context_record",
        "record_closure_report",
        "record_layer_artifacts",
        "record_verify_decision",
        "reset_backend_cache_for_tests",
        "resolve_runtime_scope",
        "save_attempt",
        "save_control_plane_operation_global",
        "save_flow_execution",
        "save_node_execution_ledger",
        "save_override_record",
        "save_phase_snapshot",
        "save_phase_state",
        "save_project",
        "save_parallelization_config",
        "save_session_run_binding_global",
        "save_story_context",
        "save_story_context_global",
        "save_story_dependency",
        "save_story_execution_lock_global",
        "upsert_story_metrics",
        "save_story_are_link",
        "update_story_are_link_kind",
    )


PUBLIC_API_NAMES: tuple[str, ...] = _build_public_api_names()

__all__ = ["PUBLIC_API_NAMES"]
